In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
import tensorflow_hub as hub

:

In [6]:
df = pd.read_csv('wine-reviews.csv' , usecols=['country' , 'description' , 'points' , 'price' , 'variety' , 'winery'])

In [ ]:
# grabe the file and load it as a table.
# read_csv convert the comman seperated values into dataframes.
df_imdb = pd.read_csv('IMDB Dataset.csv')

In [ ]:
# head func shows the first 5 rows.
df_imdb.head()

                                              review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [ ]:
# Why List Comprehension Works and the For loop fails , 
# Because the list comprehension creates a new list and assigns it to the 'sentiment' column, while the for loop tries to modify the existing 'sentiment' column in place, which is not allowed.
# In list comprehension, pandas isn't involved in the looping process at all.
# When you use a for loop, you are trying to modify the DataFrame piece-by-piece, which triggers several mistakes. 
df_imdb['sentiment'] = [1 if x == 'positive' else 0 for x in df_imdb['sentiment']]
df_imdb.head(5)

                                              review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [ ]:
# Values count method job is to look at a column of data, find all the unique items, and count exactly how many times each item appears.
# make sure the words actually turned into numbers.
print(df_imdb['sentiment'].value_counts())

sentiment
1    25000
0    25000
Name: count, dtype: int64

1    4
2    4
Name: count, dtype: int64